zstyle :plugin:fast-syntax-highlighting theme "zdharma"
typeset -g FAST_THEME_NAME="zdharma"
: ${FAST_HIGHLIGHT_STYLES[zdharmadefault]:=none}
: ${FAST_HIGHLIGHT_STYLES[zdharmaunknown-token]:=fg=red,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmareserved-word]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[zdharmaalias]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[zdharmasuffix-alias]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[zdharmabuiltin]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[zdharmafunction]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[zdharmacommand]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[zdharmaprecommand]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[zdharmacommandseparator]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[zdharmahashed-command]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[zdharmapath]:=fg=154}
: ${FAST_HIGHLIGHT_STYLES[zdharmapath_pathseparator]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[zdharmapath_pathhome]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[zdharmaglobbing]:=fg=114}
: ${FAST_HIGHLIGHT_STYLES[zdharmaglobbing-ext]:=fg=153}
: ${FAST_HIGHLIGHT_STYLES[zdharmahistory-expansion]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmasingle-hyphen-option]:=fg=177}
: ${FAST_HIGHLIGHT_STYLES[zdharmadouble-hyphen-option]:=fg=177}
: ${FAST_HIGHLIGHT_STYLES[zdharmaback-quoted-argument]:=none}
: ${FAST_HIGHLIGHT_STYLES[zdharmasingle-quoted-argument]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[zdharmadouble-quoted-argument]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[zdharmadollar-quoted-argument]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[zdharmaback-or-dollar-double-quoted-argument]:=fg=177}
: ${FAST_HIGHLIGHT_STYLES[zdharmaback-dollar-quoted-argument]:=fg=177}
: ${FAST_HIGHLIGHT_STYLES[zdharmaassign]:=none}
: ${FAST_HIGHLIGHT_STYLES[zdharmaredirection]:=none}
: ${FAST_HIGHLIGHT_STYLES[zdharmacomment]:=fg=black,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmavariable]:=none}
: ${FAST_HIGHLIGHT_STYLES[zdharmamathvar]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmamathnum]:=fg=154}
: ${FAST_HIGHLIGHT_STYLES[zdharmamatherr]:=fg=red}
: ${FAST_HIGHLIGHT_STYLES[zdharmaassign-array-bracket]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[zdharmafor-loop-variable]:=none}
: ${FAST_HIGHLIGHT_STYLES[zdharmafor-loop-number]:=fg=154}
: ${FAST_HIGHLIGHT_STYLES[zdharmafor-loop-operator]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[zdharmafor-loop-separator]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[zdharmaexec-descriptor]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmahere-string-tri]:=fg=141}
: ${FAST_HIGHLIGHT_STYLES[zdharmahere-string-text]:=bg=19}
: ${FAST_HIGHLIGHT_STYLES[zdharmahere-string-var]:=fg=177,bg=19}
: ${FAST_HIGHLIGHT_STYLES[zdharmasecondary]:=safari}
: ${FAST_HIGHLIGHT_STYLES[zdharmacase-input]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[zdharmacase-parentheses]:=fg=141}
: ${FAST_HIGHLIGHT_STYLES[zdharmacase-condition]:=bg=19}
: ${FAST_HIGHLIGHT_STYLES[zdharmacorrect-subtle]:=bg=55}
: ${FAST_HIGHLIGHT_STYLES[zdharmaincorrect-subtle]:=bg=52}
: ${FAST_HIGHLIGHT_STYLES[zdharmasubtle-separator]:=none}
: ${FAST_HIGHLIGHT_STYLES[zdharmasubtle-bg]:=bg=17}
: ${FAST_HIGHLIGHT_STYLES[zdharmapath-to-dir]:=fg=249}
: ${FAST_HIGHLIGHT_STYLES[zdharmapaired-bracket]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[zdharmabracket-level-1]:=fg=117}
: ${FAST_HIGHLIGHT_STYLES[zdharmabracket-level-2]:=fg=141}
: ${FAST_HIGHLIGHT_STYLES[zdharmabracket-level-3]:=fg=90}
: ${FAST_HIGHLIGHT_STYLES[zdharmaglobal-alias]:=bg=19}
: ${FAST_HIGHLIGHT_STYLES[zdharmasubcommand]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[zdharmasingle-sq-bracket]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[zdharmadouble-sq-bracket]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[zdharmadouble-paren]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[zdharmaoptarg-string]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[zdharmaoptarg-number]:=fg=154}
: ${FAST_HIGHLIGHT_STYLES[zdharmarecursive-base]:=fg=186}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-bin]:=fg=249}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-btm]:=fg=111}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-com]:=fg=111}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-exe]:=fg=111}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-bat]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-cmd]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-7z]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ace]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-alp]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-alz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-arc]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-arj]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-bz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-bz2]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-cpio]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-dz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-gz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-klwp]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-lha]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-lrz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-lz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-lz4]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-lzh]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-lzma]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-rar]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-rz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-t7z]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-tar]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-taz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-tbz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-tbz2]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-tgz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-tlz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-txz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-tz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-tzo]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-xz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-z]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-Z]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-zip]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ZIP]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-zoo]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-apk]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-arj]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-cab]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-deb]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ear]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-egg]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-gem]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-jad]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-jar]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-msi]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-pkg]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-rpm]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-sar]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-udeb]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-war]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-xpi]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-qcow]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-qcow2]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-vdi]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-vmdk]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-jpeg]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-jpg]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-JPG]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-bmp]:=fg=110,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-indd]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-pbm]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-pgm]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ppm]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-psd]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-tga]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-xbm]:=fg=111}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-tif]:=fg=33}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-tiff]:=fg=33}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-xpm]:=fg=36}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-bpg]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-cgm]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-CR2]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-dl]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-emf]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-eps]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mng]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-pcx]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-png]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-svg]:=fg=25}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-svgz]:=fg=25}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-webp]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-xcf]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-xwd]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-yuv]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-icc]:=fg=249}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-icm]:=fg=249}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-gif]:=fg=25,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-icns]:=fg=25,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ico]:=fg=25,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-key]:=fg=53,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-pem]:=fg=53}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-pub]:=fg=53}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-added]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-aux]:=fg=235,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-bak]:=fg=235,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-bbl]:=fg=235,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-bck]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-blg]:=fg=235,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-cache]:=fg=235,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-class]:=fg=235,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-incomplete]:=fg=235,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-log]:=fg=235,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-o]:=fg=235,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-part]:=fg=235,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-pyc]:=fg=235,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-swp]:=fg=235,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-temp]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-tmp]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-cbz]:=fg=7,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-chm]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-chrt]:=fg=14,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-db]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-djv]:=fg=7}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-djvu]:=fg=7}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-doc]:=fg=30}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-docm]:=fg=30}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-docx]:=fg=30}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-dot]:=fg=30}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-dotm]:=fg=30}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-dvi]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-epub]:=fg=7}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-fb2]:=fg=7}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-gnumeric]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ldf]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-lit]:=fg=7}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-markdown]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-md]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mdb]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mdf]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mf]:=fg=110,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mfasl]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mkd]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mobi]:=fg=7}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-odb]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-odb]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-odm]:=fg=30}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-odp]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ods]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-odt]:=fg=30}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-org]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-pages]:=fg=30}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-pdf]:=fg=7,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ppt]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-pptx]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-rtf]:=fg=30}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-sql]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-sqlite]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-txt]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-xla]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-xls]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-xlsm]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-xlsx]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-agda]:=fg=34}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-asm]:=fg=76}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-asoundrc]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-awk]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-coffee]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-cs]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-css]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-csv]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-dir_colors]:=fg=4,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-e]:=fg=245,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-enc]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-eps2]:=fg=7}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-eps3]:=fg=7}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-eps]:=fg=7}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-epsf]:=fg=7}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-epsi]:=fg=7}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-etx]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ex]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-example]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-fehbg]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-fonts]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-git]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-gitignore]:=fg=238}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-hgignore]:=fg=23,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-hgrc]:=fg=23,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-hs]:=fg=34}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-htm]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-html]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-htoprc]:=fg=23,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-info]:=fg=23,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-java]:=fg=245,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-jhtm]:=fg=29,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-jnlp]:=fg=245,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-js]:=fg=34,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-jsm]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-jsp]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-lam]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-less]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-lesshst]:=fg=23,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-lisp]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-log]:=fg=23,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-lua]:=fg=24,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-map]:=fg=2,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mf]:=fg=2,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mfasl]:=fg=2,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mi]:=fg=2,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-msmtprc]:=fg=2,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mtx]:=fg=2,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mutt]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-muttrc]:=fg=2,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-netrc]:=fg=4,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-nfo]:=fg=2,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-pacnew]:=fg=33}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ps]:=fg=7}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-sass]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-scm]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-scss]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-attheme]:=fg=5,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-diff]:=bg=7,fg=16,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-erb]:=fg=33,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-irb]:=fg=33,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-patch]:=bg=7,fg=16,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-pc]:=fg=4,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-pfa]:=fg=4,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-php]:=fg=4,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-pid]:=fg=4,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-pl]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-PL]:=fg=73,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-pm]:=fg=4,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-pod]:=fg=23,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-py]:=fg=30,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-rasi]:=fg=5,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-rb]:=fg=33,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ru]:=fg=4,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-sed]:=fg=4,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-signature]:=fg=4,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-sty]:=fg=5,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-sug]:=fg=5,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-t]:=fg=28,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-tcl]:=fg=34,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-tdesktop-pallete]:=fg=5,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-tdesktop-theme]:=fg=5,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-tdy]:=fg=5,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-tfm]:=fg=5,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-tfnt]:=fg=5,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-theme]:=fg=5,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-tk]:=fg=34,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-vim]:=fg=56}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-viminfo]:=fg=56}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-vimp]:=fg=56}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-vimrc]:=fg=56,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-bash]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-bash_history]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-bash_logout]:=fg=29,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-bash_profile]:=fg=29,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-csh]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-dash]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-fish]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ksh]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-profile]:=fg=29,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-sh]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-sh*]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-snippets]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-tcsh]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ttytterrc]:=fg=5,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-urlview]:=fg=5,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-Xauthority]:=fg=4,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-xinitrc]:=fg=4,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-Xmodmap]:=fg=4,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-Xresources]:=fg=3,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-zsh]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-zwc]:=fg=239,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-dmg]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-img]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-iso]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ISO]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mdf]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-nrg]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-vcd]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-allow]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-deny]:=fg=89}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-aux]:=fg=239}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-cfg]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-conf]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-icls]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ini]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-jidgo]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-json]:=fg=29,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-latex]:=fg=73,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mk]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-modulemap]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-n3]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-nfo]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-nix]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-nt]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ovpn]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-owl]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-qml]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-rc]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-rdf]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-reg]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-sbt]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-sls]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-tex]:=fg=73,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-textile]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-toml]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-torrent]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ttl]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-wiki]:=fg=29,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-xml]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-yaml]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-yml]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-a]:=fg=22,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-dll]:=fg=22,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-so]:=fg=22,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ffp]:=fg=69}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-gpg]:=fg=69}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-md5]:=fg=69}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-par]:=fg=69}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-sfv]:=fg=69}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-sha1]:=fg=69}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-st5]:=fg=69}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-aac]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-aiff]:=fg=31,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-alac]:=fg=31,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ape]:=fg=31,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-au]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-axa]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-dff]:=fg=31,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-dsf]:=fg=31,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-flac]:=fg=31,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-m4a]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-m4b]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-m4r]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mid]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-midi]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mka]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mp2]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mp3]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mpc]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-oga]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ogg]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ra]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-spx]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-wav]:=fg=31,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-wma]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-cue]:=fg=28}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-m3u]:=fg=28}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-m3u8]:=fg=28}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-pls]:=fg=28}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-xspf]:=fg=28}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-dat]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-fcm]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-m4]:=fg=5,italic}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mod]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-oga]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-s3m]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-S3M]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-sid]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-spl]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-wv]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-wvc]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-asf]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-avi]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-AVI]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-divx]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-flc]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-fli]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-flv]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-gl]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-m2ts]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-m2v]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-m4v]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mkv]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mov]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-MOV]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mp4]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mp4v]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mpeg]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mpg]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-nuv]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ogm]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ogv]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-qt]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-rm]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-rmvb]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-sample]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ts]:=fg=12}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-vob]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-VOB]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-webm]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-wmv]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-anx]:=fg=13,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ass]:=fg=116,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-axv]:=fg=13,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ogx]:=fg=13,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-srt]:=fg=116,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-bdf]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-dfont]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-fon]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-gsf]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-otf]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-pcf]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-pfa]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-pfb]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ttf]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-32x]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-a00]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-a52]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-a64]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-A64]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-a78]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-adf]:=fg=35}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-atr]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-cdi]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-fm2]:=fg=35}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-gb]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-gba]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-gbc]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-gel]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-gg]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ggl]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-j64]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-nds]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-nes]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-rom]:=fg=232,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-sav]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-sms]:=fg=33}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-automount]:=fg=66}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-desktop]:=fg=75}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-device]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-mount]:=fg=66}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-path]:=fg=66}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-service]:=fg=81}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-snapshot]:=fg=97}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-socket]:=fg=75}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-swap]:=fg=97}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-target]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-timer]:=fg=111}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-c]:=fg=110,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-c++]:=fg=24,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-C]:=fg=24,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-cc]:=fg=24,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-cp]:=fg=24,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-cpp]:=fg=24,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-cs]:=fg=74,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-cxx]:=fg=24,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-erl]:=fg=70,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-go]:=fg=70,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ii]:=fg=24,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ml]:=fg=70,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-rs]:=fg=73,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-rst]:=fg=73,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-swift]:=fg=73,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-pas]:=fg=73,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-scala]:=fg=70,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-clj]:=fg=76,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-el]:=fg=76,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-f]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-for]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-ftn]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-h]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-h++]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-H]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-hh]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-hpp]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-hxx]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-s]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-S]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-sx]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-tcc]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-am]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-in]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-old]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-cap]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-dmp]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-dump]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-pcap]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-am]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-in]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[zdharmaftype-old]:=fg=235}
