zstyle :plugin:fast-syntax-highlighting theme "zdharma"
typeset -g FAST_THEME_NAME="zdharma"
: ${FAST_HIGHLIGHT_STYLES[zdharmadefault]:=none}
: ${FAST_HIGHLIGHT_STYLES[zdharmaunknown-token]:=none}
: ${FAST_HIGHLIGHT_STYLES[zdharmareserved-word]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[zdharmaalias]:=fg=80}
: ${FAST_HIGHLIGHT_STYLES[zdharmasuffix-alias]:=fg=80,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmabuiltin]:=fg=80}
: ${FAST_HIGHLIGHT_STYLES[zdharmafunction]:=fg=80}
: ${FAST_HIGHLIGHT_STYLES[zdharmacommand]:=fg=80}
: ${FAST_HIGHLIGHT_STYLES[zdharmaprecommand]:=fg=80,underline}
: ${FAST_HIGHLIGHT_STYLES[zdharmacommandseparator]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[zdharmahashed-command]:=fg=80}
: ${FAST_HIGHLIGHT_STYLES[zdharmapath]:=none}
: ${FAST_HIGHLIGHT_STYLES[zdharmapath_pathseparator]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[zdharmapath_pathhome]:=fg=2}
: ${FAST_HIGHLIGHT_STYLES[zdharmapath-to-dir]:=fg=249}
: ${FAST_HIGHLIGHT_STYLES[zdharmaglobbing]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[zdharmaglobbing-ext]:=fg=153}
: ${FAST_HIGHLIGHT_STYLES[zdharmahistory-expansion]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmasingle-hyphen-option]:=fg=243}
: ${FAST_HIGHLIGHT_STYLES[zdharmadouble-hyphen-option]:=fg=243}
: ${FAST_HIGHLIGHT_STYLES[zdharmaback-quoted-argument]:=none}
: ${FAST_HIGHLIGHT_STYLES[zdharmasingle-quoted-argument]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[zdharmadouble-quoted-argument]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[zdharmadollar-quoted-argument]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[zdharmaback-or-dollar-double-quoted-argument]:=fg=4,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmaback-dollar-quoted-argument]:=fg=243}
: ${FAST_HIGHLIGHT_STYLES[zdharmaassign]:=fg=38}
: ${FAST_HIGHLIGHT_STYLES[zdharmaredirection]:=none}
: ${FAST_HIGHLIGHT_STYLES[zdharmacomment]:=fg=56,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmavariable]:=none}
: ${FAST_HIGHLIGHT_STYLES[zdharmamathvar]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmamathnum]:=fg=154}
: ${FAST_HIGHLIGHT_STYLES[zdharmamatherr]:=fg=red}
: ${FAST_HIGHLIGHT_STYLES[zdharmaassign-array-bracket]:=fg=80}
: ${FAST_HIGHLIGHT_STYLES[zdharmafor-loop-variable]:=none}
: ${FAST_HIGHLIGHT_STYLES[zdharmafor-loop-number]:=fg=154}
: ${FAST_HIGHLIGHT_STYLES[zdharmafor-loop-operator]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[zdharmafor-loop-separator]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[zdharmaexec-descriptor]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[zdharmahere-string-tri]:=fg=141}
: ${FAST_HIGHLIGHT_STYLES[zdharmahere-string-text]:=bg=19}
: ${FAST_HIGHLIGHT_STYLES[zdharmahere-string-var]:=fg=243,bg=19}
: ${FAST_HIGHLIGHT_STYLES[zdharmasecondary]:=safari}
: ${FAST_HIGHLIGHT_STYLES[zdharmacase-input]:=fg=80}
: ${FAST_HIGHLIGHT_STYLES[zdharmacase-parentheses]:=fg=141}
: ${FAST_HIGHLIGHT_STYLES[zdharmacase-condition]:=bg=19}
: ${FAST_HIGHLIGHT_STYLES[zdharmacorrect-subtle]:=bg=55}
: ${FAST_HIGHLIGHT_STYLES[zdharmaincorrect-subtle]:=bg=52}
: ${FAST_HIGHLIGHT_STYLES[zdharmasubtle-separator]:=none}
: ${FAST_HIGHLIGHT_STYLES[zdharmasubtle-bg]:=bg=17}
: ${FAST_HIGHLIGHT_STYLES[zdharmapaired-bracket]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[zdharmabracket-level-1]:=fg=241}
: ${FAST_HIGHLIGHT_STYLES[zdharmabracket-level-2]:=fg=242}
: ${FAST_HIGHLIGHT_STYLES[zdharmabracket-level-3]:=fg=243}
: ${FAST_HIGHLIGHT_STYLES[zdharmaglobal-alias]:=bg=19}
: ${FAST_HIGHLIGHT_STYLES[zdharmasubcommand]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[zdharmasingle-sq-bracket]:=fg=80}
: ${FAST_HIGHLIGHT_STYLES[zdharmadouble-sq-bracket]:=fg=80}
: ${FAST_HIGHLIGHT_STYLES[zdharmadouble-paren]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[zdharmaoptarg-string]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[zdharmaoptarg-number]:=fg=154}
: ${FAST_HIGHLIGHT_STYLES[zdharmarecursive-base]:=fg=186}
