: ${FAST_HIGHLIGHT_STYLES[ftype-lesshst]:=fg=248,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-log]:=fg=238,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-map]:=fg=248,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-nfo]:=fg=248,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-txt]:=fg=248}
: ${FAST_HIGHLIGHT_STYLES[ftype-7z]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-WARC]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-Z]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ZIP]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ace]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-alp]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-alz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-arc]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-arj]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-br]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-bz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-bz2]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-cpio]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-dz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-gz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-klwp]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-lha]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-lrz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-lz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-lz4]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-lzh]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-lzma]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-lzo]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-rar]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-rz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-s7z]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-t7z]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-tar]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-taz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-tbz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-tbz2]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-tgz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-tlz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-txz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-tz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-tzo]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-warc]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-xz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-z]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-zip]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-zipx]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-zoo]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-zpaq]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-zst]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-zstd]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-zz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-part]:=fg=244,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-r[0-9]{0,2}]:=fg=244,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-z[0-9]{0,2}]:=fg=244,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-zx[0-9]{0,2}]:=fg=244,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-apk]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-bsp]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-cab]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-crx]:=fg=74,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-deb]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-ear]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[ftype-egg]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-gem]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-jad]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-jar]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[ftype-msi]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-pak]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-pk3]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-pkg]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-rpm]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-sar]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[ftype-udeb]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-vdf]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-vpk]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-war]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[ftype-xpi]:=fg=74,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-fvd]:=fg=89}
: ${FAST_HIGHLIGHT_STYLES[ftype-qcow]:=fg=89}
: ${FAST_HIGHLIGHT_STYLES[ftype-qcow2]:=fg=89}
: ${FAST_HIGHLIGHT_STYLES[ftype-vdi]:=fg=89}
: ${FAST_HIGHLIGHT_STYLES[ftype-vhd]:=fg=89}
: ${FAST_HIGHLIGHT_STYLES[ftype-vhdx]:=fg=89}
: ${FAST_HIGHLIGHT_STYLES[ftype-vmdk]:=fg=89}
: ${FAST_HIGHLIGHT_STYLES[ftype-bin]:=fg=249}
: ${FAST_HIGHLIGHT_STYLES[ftype-com]:=fg=111}
: ${FAST_HIGHLIGHT_STYLES[ftype-ru]:=fg=111}
: ${FAST_HIGHLIGHT_STYLES[ftype-net]:=fg=111}
: ${FAST_HIGHLIGHT_STYLES[ftype-exe]:=fg=111}
: ${FAST_HIGHLIGHT_STYLES[ftype-lnk]:=fg=39}
: ${FAST_HIGHLIGHT_STYLES[ftype-dmg]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-img]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ipa]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-iso]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ISO]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-mdf]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-nrg]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-sparseimage]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-toast]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-vcd]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-vfd]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-bpg]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-cgm]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-CR2]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-dl]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[ftype-emf]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-jpeg]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[ftype-jpg]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[ftype-JPG]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[ftype-jxl]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-mng]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[ftype-pcx]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[ftype-png]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-psd]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-pxd]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-pxm]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-webp]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-xcf]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-xwd]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-yuv]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-bmp]:=fg=110,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-cdr]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[ftype-dicom]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[ftype-flif]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[ftype-indd]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[ftype-nth]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[ftype-pbm]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[ftype-pgm]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[ftype-ppm]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[ftype-tga]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[ftype-xbm]:=fg=111}
: ${FAST_HIGHLIGHT_STYLES[ftype-xpm]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[ftype-tif]:=fg=33}
: ${FAST_HIGHLIGHT_STYLES[ftype-tiff]:=fg=33}
: ${FAST_HIGHLIGHT_STYLES[ftype-TIFF]:=fg=33}
: ${FAST_HIGHLIGHT_STYLES[ftype-gif]:=fg=25,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-icns]:=fg=25,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ico]:=fg=25,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ai]:=fg=25}
: ${FAST_HIGHLIGHT_STYLES[ftype-drw]:=fg=25}
: ${FAST_HIGHLIGHT_STYLES[ftype-eps]:=fg=25}
: ${FAST_HIGHLIGHT_STYLES[ftype-eps2]:=fg=25}
: ${FAST_HIGHLIGHT_STYLES[ftype-eps3]:=fg=25}
: ${FAST_HIGHLIGHT_STYLES[ftype-epsf]:=fg=25}
: ${FAST_HIGHLIGHT_STYLES[ftype-epsi]:=fg=25}
: ${FAST_HIGHLIGHT_STYLES[ftype-ps]:=fg=25}
: ${FAST_HIGHLIGHT_STYLES[ftype-svg]:=fg=25}
: ${FAST_HIGHLIGHT_STYLES[ftype-svgz]:=fg=25}
: ${FAST_HIGHLIGHT_STYLES[ftype-icc]:=fg=249}
: ${FAST_HIGHLIGHT_STYLES[ftype-icm]:=fg=249}
: ${FAST_HIGHLIGHT_STYLES[ftype-asc]:=fg=74,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-bfe]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-enc]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-ffp]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-gpg]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-key]:=fg=74,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-md5]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-p12]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-p7s]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-par]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-pem]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-pgp]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-pub]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-sfv]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-sha1]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-sig]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-signature]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-st5]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-err]:=fg=160,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-error]:=fg=160,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-mdump]:=fg=160,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-stderr]:=fg=160,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-cbr]:=fg=15,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-cbz]:=fg=15,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-chm]:=fg=15,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-epub]:=fg=15}
: ${FAST_HIGHLIGHT_STYLES[ftype-fb2]:=fg=15}
: ${FAST_HIGHLIGHT_STYLES[ftype-lit]:=fg=15}
: ${FAST_HIGHLIGHT_STYLES[ftype-mobi]:=fg=15}
: ${FAST_HIGHLIGHT_STYLES[ftype-pdf]:=fg=15,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-PDF]:=fg=15,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-djv]:=fg=249}
: ${FAST_HIGHLIGHT_STYLES[ftype-djvu]:=fg=249}
: ${FAST_HIGHLIGHT_STYLES[ftype-dvi]:=fg=249,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-doc]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[ftype-docm]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[ftype-docx]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[ftype-dot]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[ftype-dotm]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[ftype-odb]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[ftype-odm]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[ftype-odt]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[ftype-pages]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[ftype-chrt]:=fg=14,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-numbers]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[ftype-ods]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[ftype-xla]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[ftype-xls]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[ftype-xlsm]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[ftype-xlsx]:=fg=14,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-xltm]:=fg=14,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-xltx]:=fg=14,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-odp]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-pps]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-ppt]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-ppts]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-pptx]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-pptsm]:=fg=31,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-pptxm]:=fg=31,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-btm]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[ftype-db]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[ftype-fmp12]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[ftype-fp7]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[ftype-ldf]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[ftype-localstorage]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[ftype-mdb]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[ftype-mde]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[ftype-nc]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[ftype-sqlite]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[ftype-typelib]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[ftype-accdb]:=fg=161}
: ${FAST_HIGHLIGHT_STYLES[ftype-accde]:=fg=161}
: ${FAST_HIGHLIGHT_STYLES[ftype-accdr]:=fg=161}
: ${FAST_HIGHLIGHT_STYLES[ftype-accdt]:=fg=161}
: ${FAST_HIGHLIGHT_STYLES[ftype-adoc]:=fg=246}
: ${FAST_HIGHLIGHT_STYLES[ftype-asciidoc]:=fg=246}
: ${FAST_HIGHLIGHT_STYLES[ftype-etx]:=fg=246}
: ${FAST_HIGHLIGHT_STYLES[ftype-markdown]:=fg=246}
: ${FAST_HIGHLIGHT_STYLES[ftype-md]:=fg=246}
: ${FAST_HIGHLIGHT_STYLES[ftype-mdx]:=fg=246}
: ${FAST_HIGHLIGHT_STYLES[ftype-mkd]:=fg=246}
: ${FAST_HIGHLIGHT_STYLES[ftype-pod]:=fg=246}
: ${FAST_HIGHLIGHT_STYLES[ftype-rst]:=fg=246}
: ${FAST_HIGHLIGHT_STYLES[ftype-wiki]:=fg=246}
: ${FAST_HIGHLIGHT_STYLES[ftype-info]:=fg=249,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-latex]:=fg=249,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-norg]:=fg=249,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-org]:=fg=249,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-tex]:=fg=249,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-textile]:=fg=249,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-awk]:=fg=103}
: ${FAST_HIGHLIGHT_STYLES[ftype-bash]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-bash_history]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-bash_login]:=fg=103,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-bash_logout]:=fg=103,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-bash_profile]:=fg=103,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-csh]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-dash]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-fish]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ksh]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-profile]:=fg=103,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-sed]:=fg=103,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-zlogin]:=fg=103,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-zlogout]:=fg=103,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-zprofile]:=fg=103,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-zshenv]:=fg=103,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-sh]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-sh*]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-tcsh]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-zsh]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-zwc]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[ftype-bat]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-cmd]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-astro]:=fg=250,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ejs]:=fg=250,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-mustache]:=fg=250,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-pug]:=fg=250,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-svelte]:=fg=250,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-vue]:=fg=250,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-css]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-less]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-sass]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-scss]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-htm]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-html]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-jhtm]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-mht]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-diff]:=bg=7,fg=16,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-patch]:=bg=7,fg=16,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-attheme]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-colors]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-rasi]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-sty]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-sug]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-tdesktop-pallete]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-tdesktop-theme]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-tdy]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-tfm]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-tfnt]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-theme]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-allow]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[ftype-deny]:=fg=89}
: ${FAST_HIGHLIGHT_STYLES[ftype-icls]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-jidgo]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-modulemap]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-n3]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-nt]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-owl]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-qml]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-rdf]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-torrent]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-ttl]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-dhall]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-mk]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-rake]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-sbt]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-cfg]:=fg=2}
: ${FAST_HIGHLIGHT_STYLES[ftype-conf]:=fg=2}
: ${FAST_HIGHLIGHT_STYLES[ftype-hgignore]:=fg=2,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-hgrc]:=fg=2}
: ${FAST_HIGHLIGHT_STYLES[ftype-htoprc]:=fg=2}
: ${FAST_HIGHLIGHT_STYLES[ftype-ini]:=fg=2}
: ${FAST_HIGHLIGHT_STYLES[ftype-json]:=fg=2}
: ${FAST_HIGHLIGHT_STYLES[ftype-mf]:=fg=2}
: ${FAST_HIGHLIGHT_STYLES[ftype-msmtprc]:=fg=2}
: ${FAST_HIGHLIGHT_STYLES[ftype-muttrc]:=fg=33}
: ${FAST_HIGHLIGHT_STYLES[ftype-netrc]:=fg=33,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-nix]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-ovpn]:=fg=33,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-pacnew]:=fg=33,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-prisma]:=fg=33,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-psf]:=fg=2,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-rc]:=fg=2,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-reg]:=fg=33,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-sls]:=fg=2,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-vil]:=fg=2}
: ${FAST_HIGHLIGHT_STYLES[ftype-xkb]:=fg=2,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-Xauthority]:=fg=4,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-xinitrc]:=fg=4,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-Xmodmap]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[ftype-Xresources]:=fg=33,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-kak]:=fg=56}
: ${FAST_HIGHLIGHT_STYLES[ftype-vim]:=fg=56}
: ${FAST_HIGHLIGHT_STYLES[ftype-viminfo]:=fg=56}
: ${FAST_HIGHLIGHT_STYLES[ftype-vimp]:=fg=56}
: ${FAST_HIGHLIGHT_STYLES[ftype-vimrc]:=fg=56,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-snippets]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-bib]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-dtd]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-epf]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-fxml]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-hjson]:=fg=29,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-json5]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-jsonc]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-jsonl]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-jsonnet]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-libsonnet]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-msg]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-ndjson]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-pgn]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-plist]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-rdata]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-RData]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-rnc]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-rng]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-rss]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-sgml]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-tmTheme]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-toml]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-xml]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-xsd]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-yaml]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-yml]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-csv]:=fg=28}
: ${FAST_HIGHLIGHT_STYLES[ftype-tsv]:=fg=28}
: ${FAST_HIGHLIGHT_STYLES[ftype-a]:=fg=22,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-dll]:=fg=22,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-o]:=fg=236,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-rlib]:=fg=236,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-so]:=fg=22,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-aac]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-axa]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-m4a]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-m4b]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-m4r]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-mka]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-mp2]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-mp3]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-mp4a]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-mpc]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-oga]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-ogg]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-opus]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-ra]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-spx]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-wma]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-alac]:=fg=34,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-ape]:=fg=34,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-cda]:=fg=34,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-flac]:=fg=34,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-pcm]:=fg=34,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-wav]:=fg=34,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-dff]:=fg=36,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-dsf]:=fg=36,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-mid]:=fg=37,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-midi]:=fg=37,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-3ga]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[ftype-aiff]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[ftype-amr]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[ftype-au]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[ftype-caf]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[ftype-dat]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[ftype-dts]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[ftype-fcm]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[ftype-m4]:=fg=5,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-mod]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[ftype-s3m]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-S3M]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-sid]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[ftype-sid]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-spl]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[ftype-wv]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[ftype-wvc]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[ftype-IFO]:=fg=28}
: ${FAST_HIGHLIGHT_STYLES[ftype-cue]:=fg=28,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-m3u]:=fg=28,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-m3u8]:=fg=28,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-pls]:=fg=28,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-xspf]:=fg=28,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-avi]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-AVI]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-divx]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-flc]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-fli]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-gl]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-m2ts]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-m2v]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-m4v]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-mjpeg]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-mkv]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-mov]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-MOV]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-mp4]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-mp4v]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-mpeg]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-mpg]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-nuv]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ogm]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-qt]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-rm]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-rmvb]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-sample]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ts]:=fg=75}
: ${FAST_HIGHLIGHT_STYLES[ftype-vob]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-VOB]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-wmv]:=fg=75}
: ${FAST_HIGHLIGHT_STYLES[ftype-3g2]:=fg=75,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-3gp]:=fg=75,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-asf]:=fg=75,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-f4v]:=fg=75,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-flv]:=fg=75,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-gp3]:=fg=75,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-gp4]:=fg=75,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-ogv]:=fg=75,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-webm]:=fg=75,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-anx]:=fg=13,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-axv]:=fg=13,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ogx]:=fg=13,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ass]:=fg=116,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-srt]:=fg=116,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ssa]:=fg=116,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-sub]:=fg=116,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-sup]:=fg=116,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-vtt]:=fg=116,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-afm]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-bdf]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-dfont]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-fnt]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-fon]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-gsf]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-otf]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-pcf]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-pfa]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-PFA]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-pfb]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-pfm]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ttf]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-woff]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-woff2]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-32x]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[ftype-A64]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[ftype-a00]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[ftype-a52]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[ftype-a64]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[ftype-a78]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[ftype-adf]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[ftype-atr]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[ftype-cdi]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[ftype-fm2]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[ftype-gb]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[ftype-gba]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[ftype-gbc]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[ftype-gel]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[ftype-gg]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[ftype-ggl]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[ftype-j64]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[ftype-nds]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[ftype-nes]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[ftype-rom]:=fg=222,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-sav]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[ftype-sms]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[ftype-st]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[ftype-ipk]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[ftype-automount]:=fg=66}
: ${FAST_HIGHLIGHT_STYLES[ftype-desktop]:=fg=75}
: ${FAST_HIGHLIGHT_STYLES[ftype-device]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[ftype-mount]:=fg=66}
: ${FAST_HIGHLIGHT_STYLES[ftype-path]:=fg=66}
: ${FAST_HIGHLIGHT_STYLES[ftype-service]:=fg=81}
: ${FAST_HIGHLIGHT_STYLES[ftype-snapshot]:=fg=97}
: ${FAST_HIGHLIGHT_STYLES[ftype-socket]:=fg=75}
: ${FAST_HIGHLIGHT_STYLES[ftype-swap]:=fg=95}
: ${FAST_HIGHLIGHT_STYLES[ftype-target]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[ftype-timer]:=fg=111}
: ${FAST_HIGHLIGHT_STYLES[ftype-pid]:=fg=1,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-state]:=fg=1,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-agda]:=fg=34}
: ${FAST_HIGHLIGHT_STYLES[ftype-agdai]:=fg=34}
: ${FAST_HIGHLIGHT_STYLES[ftype-c++]:=fg=24,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-C]:=fg=24,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-c]:=fg=110,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-tcc]:=fg=110,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-M]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[ftype-m]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[ftype-cc]:=fg=24,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-clj]:=fg=64,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-cljc]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[ftype-cljs]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[ftype-cljw]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[ftype-cp]:=fg=24,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-cpp]:=fg=24,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-cr]:=fg=81}
: ${FAST_HIGHLIGHT_STYLES[ftype-cs]:=fg=81}
: ${FAST_HIGHLIGHT_STYLES[ftype-cxx]:=fg=24,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-erl]:=fg=70,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-f03]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-F03]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-f]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-F]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-f08]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-F08]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-f90]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-F90]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-f95]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-F95]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-fnl]:=fg=64,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-for]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-ftn]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-go]:=fg=70,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-lagda]:=fg=34}
: ${FAST_HIGHLIGHT_STYLES[ftype-lagda.md]:=fg=34}
: ${FAST_HIGHLIGHT_STYLES[ftype-lagda.rst]:=fg=34}
: ${FAST_HIGHLIGHT_STYLES[ftype-lagda.tex]:=fg=34}
: ${FAST_HIGHLIGHT_STYLES[ftype-ml]:=fg=70,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-pas]:=fg=73,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-ctp]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[ftype-ctp]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[ftype-php]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[ftype-pl]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[ftype-PL]:=fg=73,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-pm]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[ftype-py]:=fg=30,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-r]:=fg=28}
: ${FAST_HIGHLIGHT_STYLES[ftype-R]:=fg=28}
: ${FAST_HIGHLIGHT_STYLES[ftype-rb]:=fg=33,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-rs]:=fg=73,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-sc]:=fg=70,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-scala]:=fg=70,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-t]:=fg=28,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-tcl]:=fg=34,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-tk]:=fg=34,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-xsh]:=fg=33,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-scpt]:=fg=219,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-swift]:=fg=219,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-comp]:=fg=142}
: ${FAST_HIGHLIGHT_STYLES[ftype-frag]:=fg=142}
: ${FAST_HIGHLIGHT_STYLES[ftype-glsl]:=fg=70,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-spv]:=fg=136}
: ${FAST_HIGHLIGHT_STYLES[ftype-vert]:=fg=142}
: ${FAST_HIGHLIGHT_STYLES[ftype-wgsl]:=fg=97}
: ${FAST_HIGHLIGHT_STYLES[ftype-vb]:=fg=81}
: ${FAST_HIGHLIGHT_STYLES[ftype-vba]:=fg=81}
: ${FAST_HIGHLIGHT_STYLES[ftype-vbs]:=fg=81}
: ${FAST_HIGHLIGHT_STYLES[ftype-cjs]:=fg=74,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-coffee]:=fg=74,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-dart]:=fg=74,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-js]:=fg=74,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-jsx]:=fg=74,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-mjs]:=fg=74,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-ts]:=fg=74,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-tsx]:=fg=74,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-gs]:=fg=74,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-lua]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-moon]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-cl]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-el]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[ftype-elc]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[ftype-eln]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[ftype-lisp]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-ml]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-rkt]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-scm]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-ahk]:=fg=33,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-asm]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[ftype-e]:=fg=245,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-erb]:=fg=33,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ex]:=fg=36}
: ${FAST_HIGHLIGHT_STYLES[ftype-example]:=fg=36}
: ${FAST_HIGHLIGHT_STYLES[ftype-fehbg]:=fg=36}
: ${FAST_HIGHLIGHT_STYLES[ftype-fonts]:=fg=36}
: ${FAST_HIGHLIGHT_STYLES[ftype-gemspec]:=fg=33,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-gnumeric]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[ftype-hi]:=fg=34}
: ${FAST_HIGHLIGHT_STYLES[ftype-hs]:=fg=34}
: ${FAST_HIGHLIGHT_STYLES[ftype-ipynb]:=fg=33,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-irb]:=fg=33,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-lhs]:=fg=34,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-mf]:=fg=110,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-nim]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[ftype-nimble]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[ftype-pc]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[ftype-pfa]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[ftype-sx]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[ftype-tf]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-tfstate]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-tfvars]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-v]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[ftype-vala]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[ftype-vapi]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[ftype-zig]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[ftype-msql]:=fg=83}
: ${FAST_HIGHLIGHT_STYLES[ftype-mysql]:=fg=83}
: ${FAST_HIGHLIGHT_STYLES[ftype-pgsql]:=fg=83}
: ${FAST_HIGHLIGHT_STYLES[ftype-prql]:=fg=83}
: ${FAST_HIGHLIGHT_STYLES[ftype-sql]:=fg=83}
: ${FAST_HIGHLIGHT_STYLES[ftype-java]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-jsm]:=fg=245}
: ${FAST_HIGHLIGHT_STYLES[ftype-jnlp]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-jsp]:=fg=245}
: ${FAST_HIGHLIGHT_STYLES[ftype-stl]:=fg=216}
: ${FAST_HIGHLIGHT_STYLES[ftype-dwg]:=fg=216}
: ${FAST_HIGHLIGHT_STYLES[ftype-ply]:=fg=216}
: ${FAST_HIGHLIGHT_STYLES[ftype-wrl]:=fg=216}
: ${FAST_HIGHLIGHT_STYLES[ftype-8xp]:=fg=204}
: ${FAST_HIGHLIGHT_STYLES[ftype-8eu]:=fg=204}
: ${FAST_HIGHLIGHT_STYLES[ftype-82p]:=fg=204}
: ${FAST_HIGHLIGHT_STYLES[ftype-83p]:=fg=204}
: ${FAST_HIGHLIGHT_STYLES[ftype-8xe]:=fg=204}
: ${FAST_HIGHLIGHT_STYLES[ftype-h]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[ftype-H]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[ftype-h++]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[ftype-hh]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[ftype-hpp]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[ftype-hxx]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[ftype-s]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[ftype-S]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[ftype-git]:=fg=36}
: ${FAST_HIGHLIGHT_STYLES[ftype-gitattributes]:=fg=36}
: ${FAST_HIGHLIGHT_STYLES[ftype-github]:=fg=36}
: ${FAST_HIGHLIGHT_STYLES[ftype-gitignore]:=fg=240}
: ${FAST_HIGHLIGHT_STYLES[ftype-am]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[ftype-hin]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[ftype-in]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[ftype-m4]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[ftype-old]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[ftype-out]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[ftype-scan]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[ftype-SKIP]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[ftype-containerignore]:=fg=240}
: ${FAST_HIGHLIGHT_STYLES[ftype-dockerignore]:=fg=240}
: ${FAST_HIGHLIGHT_STYLES[ftype-aria2]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-cap]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-dmp]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-dump]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-pcap]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-stackdump]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-zcompdump]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-eml]:=fg=90,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-http]:=fg=90,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ttytterrc]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-urlview]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-webloc]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-added]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[ftype-archimate]:=fg=57}
: ${FAST_HIGHLIGHT_STYLES[ftype-aux]:=fg=244,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-bbl]:=fg=244,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-blg]:=fg=244,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-cache]:=fg=244,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-car]:=fg=57}
: ${FAST_HIGHLIGHT_STYLES[ftype-CFUserTextEncoding]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[ftype-class]:=fg=244,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-DS_Store]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[ftype-dylib]:=fg=241}
: ${FAST_HIGHLIGHT_STYLES[ftype-entitlements]:=1}
: ${FAST_HIGHLIGHT_STYLES[ftype-ex]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[ftype-example]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[ftype-feature]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[ftype-ics]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[ftype-incomplete]:=fg=244,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-localized]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[ftype-mfasl]:=fg=244,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-nib]:=fg=57}
: ${FAST_HIGHLIGHT_STYLES[ftype-orig]:=fg=241,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-pbxproj]:=1}
: ${FAST_HIGHLIGHT_STYLES[ftype-pyc]:=fg=244,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-storyboard]:=fg=196}
: ${FAST_HIGHLIGHT_STYLES[ftype-strings]:=1}
: ${FAST_HIGHLIGHT_STYLES[ftype-tg]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[ftype-vcard]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[ftype-vcf]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[ftype-xcconfig]:=1}
: ${FAST_HIGHLIGHT_STYLES[ftype-xcsettings]:=1}
: ${FAST_HIGHLIGHT_STYLES[ftype-xcuserstate]:=1}
: ${FAST_HIGHLIGHT_STYLES[ftype-xcworkspacedata]:=1}
: ${FAST_HIGHLIGHT_STYLES[ftype-bak]:=fg=247,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-bck]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[ftype-ii]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[ftype-sassc]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[ftype-swo]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[ftype-swp]:=fg=247,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-temp]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[ftype-tmp]:=fg=247}
