: ${FAST_HIGHLIGHT_STYLES[ftype-bin]:=fg=249}
: ${FAST_HIGHLIGHT_STYLES[ftype-btm]:=fg=111}
: ${FAST_HIGHLIGHT_STYLES[ftype-com]:=fg=111}
: ${FAST_HIGHLIGHT_STYLES[ftype-exe]:=fg=111}
: ${FAST_HIGHLIGHT_STYLES[ftype-bat]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-cmd]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-7z]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ace]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-alp]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-alz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-arc]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-arj]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-bz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-bz2]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-cpio]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-dz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-gz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-klwp]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-lha]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-lrz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-lz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-lz4]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-lzh]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-lzma]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-rar]:=fg=80}
: ${FAST_HIGHLIGHT_STYLES[ftype-rz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-t7z]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-tar]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-taz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-tbz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-tbz2]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-tgz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-tlz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-txz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-tz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-tzo]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-xz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-z]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-Z]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-zip]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ZIP]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-zoo]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-apk]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-arj]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[ftype-cab]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-deb]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-ear]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[ftype-egg]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-gem]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-jad]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-jar]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[ftype-msi]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-pkg]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-rpm]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-sar]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[ftype-udeb]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-war]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[ftype-xpi]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-qcow]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-qcow2]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-vdi]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-vmdk]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-jpeg]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[ftype-jpg]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[ftype-JPG]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[ftype-bmp]:=fg=110,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-indd]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[ftype-pbm]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[ftype-pgm]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[ftype-ppm]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[ftype-psd]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[ftype-tga]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[ftype-xbm]:=fg=111}
: ${FAST_HIGHLIGHT_STYLES[ftype-tif]:=fg=33}
: ${FAST_HIGHLIGHT_STYLES[ftype-tiff]:=fg=33}
: ${FAST_HIGHLIGHT_STYLES[ftype-xpm]:=fg=36}
: ${FAST_HIGHLIGHT_STYLES[ftype-bpg]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-cgm]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-CR2]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-dl]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[ftype-emf]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-eps]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-mng]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[ftype-pcx]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[ftype-png]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-svg]:=fg=25}
: ${FAST_HIGHLIGHT_STYLES[ftype-svgz]:=fg=25}
: ${FAST_HIGHLIGHT_STYLES[ftype-webp]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-xcf]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-xwd]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-yuv]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-icc]:=fg=249}
: ${FAST_HIGHLIGHT_STYLES[ftype-icm]:=fg=249}
: ${FAST_HIGHLIGHT_STYLES[ftype-gif]:=fg=25,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-icns]:=fg=25,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ico]:=fg=25,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-key]:=fg=53,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-pem]:=fg=53}
: ${FAST_HIGHLIGHT_STYLES[ftype-pub]:=fg=53}
: ${FAST_HIGHLIGHT_STYLES[ftype-added]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[ftype-aux]:=fg=235,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-bak]:=fg=235,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-bbl]:=fg=235,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-bck]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[ftype-blg]:=fg=235,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-cache]:=fg=235,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-class]:=fg=235,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-incomplete]:=fg=235,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-log]:=fg=235,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-o]:=fg=235,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-part]:=fg=235,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-pyc]:=fg=235,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-swp]:=fg=235,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-temp]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[ftype-tmp]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[ftype-cbz]:=fg=7,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-chm]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[ftype-chrt]:=fg=14,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-db]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[ftype-djv]:=fg=7}
: ${FAST_HIGHLIGHT_STYLES[ftype-djvu]:=fg=7}
: ${FAST_HIGHLIGHT_STYLES[ftype-doc]:=fg=30}
: ${FAST_HIGHLIGHT_STYLES[ftype-docm]:=fg=30}
: ${FAST_HIGHLIGHT_STYLES[ftype-docx]:=fg=30}
: ${FAST_HIGHLIGHT_STYLES[ftype-dot]:=fg=30}
: ${FAST_HIGHLIGHT_STYLES[ftype-dotm]:=fg=30}
: ${FAST_HIGHLIGHT_STYLES[ftype-dvi]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[ftype-epub]:=fg=7}
: ${FAST_HIGHLIGHT_STYLES[ftype-fb2]:=fg=7}
: ${FAST_HIGHLIGHT_STYLES[ftype-gnumeric]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[ftype-ldf]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[ftype-lit]:=fg=7}
: ${FAST_HIGHLIGHT_STYLES[ftype-markdown]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[ftype-md]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[ftype-mdb]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[ftype-mdf]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[ftype-mf]:=fg=110,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-mfasl]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[ftype-mkd]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[ftype-mobi]:=fg=7}
: ${FAST_HIGHLIGHT_STYLES[ftype-odb]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-odb]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[ftype-odm]:=fg=30}
: ${FAST_HIGHLIGHT_STYLES[ftype-odp]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-ods]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-odt]:=fg=30}
: ${FAST_HIGHLIGHT_STYLES[ftype-org]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[ftype-pages]:=fg=30}
: ${FAST_HIGHLIGHT_STYLES[ftype-pdf]:=fg=7,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ppt]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-pptx]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-rtf]:=fg=30}
: ${FAST_HIGHLIGHT_STYLES[ftype-sql]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[ftype-sqlite]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[ftype-txt]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-xla]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[ftype-xls]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[ftype-xlsm]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[ftype-xlsx]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[ftype-agda]:=fg=34}
: ${FAST_HIGHLIGHT_STYLES[ftype-asm]:=fg=76}
: ${FAST_HIGHLIGHT_STYLES[ftype-asoundrc]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-awk]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-coffee]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-cs]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-css]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-csv]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-dir_colors]:=fg=4,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-e]:=fg=245,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-enc]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-eps2]:=fg=7}
: ${FAST_HIGHLIGHT_STYLES[ftype-eps3]:=fg=7}
: ${FAST_HIGHLIGHT_STYLES[ftype-eps]:=fg=7}
: ${FAST_HIGHLIGHT_STYLES[ftype-epsf]:=fg=7}
: ${FAST_HIGHLIGHT_STYLES[ftype-epsi]:=fg=7}
: ${FAST_HIGHLIGHT_STYLES[ftype-etx]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-ex]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-example]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-fehbg]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-fonts]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-git]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-gitignore]:=fg=238}
: ${FAST_HIGHLIGHT_STYLES[ftype-hgignore]:=fg=23,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-hgrc]:=fg=23,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-hs]:=fg=34}
: ${FAST_HIGHLIGHT_STYLES[ftype-htm]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-html]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-htoprc]:=fg=23,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-info]:=fg=23,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-java]:=fg=245,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-jhtm]:=fg=29,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-jnlp]:=fg=245,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-js]:=fg=34,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-jsm]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-jsp]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-lam]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-less]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-lesshst]:=fg=23,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-lisp]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-log]:=fg=23,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-lua]:=fg=24,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-map]:=fg=2,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-mf]:=fg=2,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-mfasl]:=fg=2,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-mi]:=fg=2,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-msmtprc]:=fg=2,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-mtx]:=fg=2,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-mutt]:=fg=6,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-muttrc]:=fg=2,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-netrc]:=fg=4,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-nfo]:=fg=2,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-pacnew]:=fg=33}
: ${FAST_HIGHLIGHT_STYLES[ftype-ps]:=fg=7}
: ${FAST_HIGHLIGHT_STYLES[ftype-sass]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-scm]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[ftype-scss]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-attheme]:=fg=5,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-diff]:=bg=7,fg=16,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-erb]:=fg=33,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-irb]:=fg=33,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-patch]:=bg=7,fg=16,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-pc]:=fg=4,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-pfa]:=fg=4,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-php]:=fg=4,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-pid]:=fg=4,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-pl]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[ftype-PL]:=fg=73,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-pm]:=fg=4,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-pod]:=fg=23,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-py]:=fg=30,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-rasi]:=fg=5,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-rb]:=fg=33,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-ru]:=fg=4,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-sed]:=fg=4,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-signature]:=fg=4,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-sty]:=fg=5,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-sug]:=fg=5,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-t]:=fg=28,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-tcl]:=fg=34,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-tdesktop-pallete]:=fg=5,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-tdesktop-theme]:=fg=5,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-tdy]:=fg=5,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-tfm]:=fg=5,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-tfnt]:=fg=5,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-theme]:=fg=5,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-tk]:=fg=34,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-vim]:=fg=56}
: ${FAST_HIGHLIGHT_STYLES[ftype-viminfo]:=fg=56}
: ${FAST_HIGHLIGHT_STYLES[ftype-vimp]:=fg=56}
: ${FAST_HIGHLIGHT_STYLES[ftype-vimrc]:=fg=56,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-bash]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-bash_history]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-bash_logout]:=fg=29,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-bash_profile]:=fg=29,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-csh]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-dash]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-fish]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ksh]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-profile]:=fg=29,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-sh]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-sh*]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-snippets]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-tcsh]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ttytterrc]:=fg=5,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-urlview]:=fg=5,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-Xauthority]:=fg=4,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-xinitrc]:=fg=4,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-Xmodmap]:=fg=4,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-Xresources]:=fg=3,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-zsh]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-zwc]:=fg=239,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-dmg]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-img]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-iso]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ISO]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-mdf]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-nrg]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-vcd]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-allow]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[ftype-deny]:=fg=89}
: ${FAST_HIGHLIGHT_STYLES[ftype-aux]:=fg=239}
: ${FAST_HIGHLIGHT_STYLES[ftype-cfg]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-conf]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-icls]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-ini]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-jidgo]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-json]:=fg=29,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-latex]:=fg=73,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-mk]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-modulemap]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-n3]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-nfo]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-nix]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-nt]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-ovpn]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-owl]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-qml]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-rc]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-rdf]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-reg]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-sbt]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-sls]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-tex]:=fg=73,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-textile]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-toml]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-torrent]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-ttl]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-wiki]:=fg=29,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-xml]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-yaml]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[ftype-yml]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-a]:=fg=22,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-dll]:=fg=22,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-so]:=fg=22,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ffp]:=fg=69}
: ${FAST_HIGHLIGHT_STYLES[ftype-gpg]:=fg=69}
: ${FAST_HIGHLIGHT_STYLES[ftype-md5]:=fg=69}
: ${FAST_HIGHLIGHT_STYLES[ftype-par]:=fg=69}
: ${FAST_HIGHLIGHT_STYLES[ftype-sfv]:=fg=69}
: ${FAST_HIGHLIGHT_STYLES[ftype-sha1]:=fg=69}
: ${FAST_HIGHLIGHT_STYLES[ftype-st5]:=fg=69}
: ${FAST_HIGHLIGHT_STYLES[ftype-aac]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-aiff]:=fg=31,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-alac]:=fg=31,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ape]:=fg=31,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-au]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-axa]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-dff]:=fg=31,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-dsf]:=fg=31,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-flac]:=fg=31,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-m4a]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-m4b]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-m4r]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-mid]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-midi]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-mka]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-mp2]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-mp3]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-mpc]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-oga]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-ogg]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-ra]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-spx]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-wav]:=fg=31,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-wma]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[ftype-cue]:=fg=28}
: ${FAST_HIGHLIGHT_STYLES[ftype-m3u]:=fg=28}
: ${FAST_HIGHLIGHT_STYLES[ftype-m3u8]:=fg=28}
: ${FAST_HIGHLIGHT_STYLES[ftype-pls]:=fg=28}
: ${FAST_HIGHLIGHT_STYLES[ftype-xspf]:=fg=28}
: ${FAST_HIGHLIGHT_STYLES[ftype-dat]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[ftype-fcm]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[ftype-m4]:=fg=5,italic}
: ${FAST_HIGHLIGHT_STYLES[ftype-mod]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[ftype-oga]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[ftype-s3m]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-S3M]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-sid]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-spl]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[ftype-wv]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[ftype-wvc]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[ftype-asf]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-avi]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-AVI]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-divx]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-flc]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-fli]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-flv]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-gl]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-m2ts]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-m2v]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-m4v]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-mkv]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-mov]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-MOV]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-mp4]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-mp4v]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-mpeg]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-mpg]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-nuv]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ogm]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ogv]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-qt]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-rm]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-rmvb]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-sample]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ts]:=fg=12}
: ${FAST_HIGHLIGHT_STYLES[ftype-vob]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-VOB]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-webm]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-wmv]:=fg=12,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-anx]:=fg=13,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ass]:=fg=116,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-axv]:=fg=13,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-ogx]:=fg=13,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-srt]:=fg=116,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-bdf]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-dfont]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-fon]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-gsf]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-otf]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-pcf]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-pfa]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-pfb]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[ftype-ttf]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-32x]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[ftype-a00]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[ftype-a52]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[ftype-a64]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[ftype-A64]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[ftype-a78]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[ftype-adf]:=fg=35}
: ${FAST_HIGHLIGHT_STYLES[ftype-atr]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[ftype-cdi]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[ftype-fm2]:=fg=35}
: ${FAST_HIGHLIGHT_STYLES[ftype-gb]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[ftype-gba]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[ftype-gbc]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[ftype-gel]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[ftype-gg]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[ftype-ggl]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[ftype-j64]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[ftype-nds]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[ftype-nes]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[ftype-rom]:=fg=232,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-sav]:=fg=232}
: ${FAST_HIGHLIGHT_STYLES[ftype-sms]:=fg=33}
: ${FAST_HIGHLIGHT_STYLES[ftype-automount]:=fg=66}
: ${FAST_HIGHLIGHT_STYLES[ftype-desktop]:=fg=75}
: ${FAST_HIGHLIGHT_STYLES[ftype-device]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[ftype-mount]:=fg=66}
: ${FAST_HIGHLIGHT_STYLES[ftype-path]:=fg=66}
: ${FAST_HIGHLIGHT_STYLES[ftype-service]:=fg=81}
: ${FAST_HIGHLIGHT_STYLES[ftype-snapshot]:=fg=97}
: ${FAST_HIGHLIGHT_STYLES[ftype-socket]:=fg=75}
: ${FAST_HIGHLIGHT_STYLES[ftype-swap]:=fg=97}
: ${FAST_HIGHLIGHT_STYLES[ftype-target]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[ftype-timer]:=fg=111}
: ${FAST_HIGHLIGHT_STYLES[ftype-c]:=fg=110,bold}
: ${FAST_HIGHLIGHT_STYLES[ftype-c++]:=fg=24,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-C]:=fg=24,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-cc]:=fg=24,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-cp]:=fg=24,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-cpp]:=fg=24,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-cs]:=fg=74,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-cxx]:=fg=24,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-erl]:=fg=70,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-go]:=fg=70,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-ii]:=fg=24,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-ml]:=fg=70,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-rs]:=fg=73,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-rst]:=fg=73,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-swift]:=fg=73,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-pas]:=fg=73,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-scala]:=fg=70,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-clj]:=fg=76,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-el]:=fg=76,underline}
: ${FAST_HIGHLIGHT_STYLES[ftype-f]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-for]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-ftn]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-h]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-h++]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-H]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-hh]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-hpp]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-hxx]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-s]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-S]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-sx]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-tcc]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-am]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[ftype-in]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[ftype-old]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[ftype-cap]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-dmp]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-dump]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[ftype-pcap]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[ftype-am]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[ftype-in]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[ftype-old]:=fg=235}
